#!/usr/bin/env python

import httplib
import httplib2
import json
import subprocess
import uuid

import yar.util.basic


def create_database():

    database = "das"+str(uuid.uuid4()).replace("-", "")

    exit_code = subprocess.call([
        "key_store_installer",
        "--database=%s" % database,
        "--create=True",
        "--delete=False",
    ])
    if 0 != exit_code:
        return None

    return database


def delete_database(database):
    http_client = httplib2.Http()
    response, content = http_client.request(
        "http://127.0.0.1:5984/%s" % database,
        "DELETE")
    return httplib.OK == response.status


def create_basic_creds(principal):
    api_key = yar.util.basic.APIKey.generate()
    rv = {
        "_id": api_key,
        "principal": principal,
        "type": "creds_v1.0",
        "is_deleted": False,
        "basic": {
            "api_key": api_key,
        },
    }
    return rv


def save_lots_of_creds_in_database(database, principal, number_of_creds):

    http_client = httplib2.Http()

    #
    # using CouchDB's bulk insertion api provides signifiant performance
    # improvements over inserting credentials one by one. docs for the API
    # can be found at:
    #
    #   http://couchdb.readthedocs.org/en/latest/api/database/bulk-api.html?highlight=_bulk_docs#db-bulk-docs
    #
    body = {
        "docs": [create_basic_creds(principal) for i in range(0, number_of_creds)],
    }

    body_as_json = json.dumps(body)
    headers = {
        "Content-type": "application/json; charset=utf8",
        "Content-length": str(len(body_as_json)),
    }
    response, content = http_client.request(
        "http://127.0.0.1:5984/%s/_bulk_docs" % database,
        "POST",
        body=body_as_json,
        headers=headers)
    if httplib.CREATED != response.status:
        pass

    #
    # now the creds have been saved, let's query the database to
    # get a sense of its size. API docs for this database request
    # can be found at:
    #
    #   http://couchdb.readthedocs.org/en/latest/api/database/common.html#get--db
    #
    body_as_json = json.dumps(body)
    headers = {
        "Content-type": "application/json; charset=utf8",
        "Content-length": str(len(body_as_json)),
    }
    response, content = http_client.request(
        "http://127.0.0.1:5984/%s" % database,
        "GET")
    if httplib.OK != response.status:
        pass

    content = json.loads(content)
    return (content["doc_count"], content["data_size"], content["disk_size"])


def bytes_to_megabytes(bytes):
    """Convert an integer value representing a number of bytes into another
    integer value representing the equivalent number of megabytes."""
    return int(bytes / (1024.0 * 1024.0))


if __name__ == "__main__":
    database = create_database()

    principal = "dave@example.com"

    number_of_creds_to_add = [
        10000,
        90000,
    ]
    # number_of_creds_to_add.extend([100000] * 9)

    print "Number of Credentials\tData Size (MB)\tDisk Size (MB)"
    for number_of_creds in number_of_creds_to_add:
        (number_creds, data_size, disk_size) = save_lots_of_creds_in_database(
            database,
            principal,
            number_of_creds)
        print "%s\t%s\t%s" % (
            number_creds,
            bytes_to_megabytes(data_size),
            bytes_to_megabytes(disk_size))

    delete_database(database)
